.TH "corectl" "1" "" " " ""  ""


.SH NAME
.PP
corectl\-kill \- Halts one or more running CoreOS instances


.SH SYNOPSIS
.PP
\fBcorectl kill\fP [OPTIONS]


.SH DESCRIPTION
.PP
Halts one or more running CoreOS instances


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
    halts all running instances


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
