.TH "corectl" "1" "" " " ""  ""


.SH NAME
.PP
corectl \- CoreOS over OSX made simple.


.SH SYNOPSIS
.PP
\fBcorectl\fP [OPTIONS]


.SH DESCRIPTION
.PP
CoreOS over OSX made simple.
❯❯❯ 
\[la]http://github.com/TheNewNormal/corectl\[ra]


.SH OPTIONS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users


.SH SEE ALSO
.PP
, \fBcorectl\-kill(1)\fP, \fBcorectl\-load(1)\fP, \fBcorectl\-ls(1)\fP, \fBcorectl\-ps(1)\fP, \fBcorectl\-pull(1)\fP, \fBcorectl\-put(1)\fP, \fBcorectl\-query(1)\fP, \fBcorectl\-rm(1)\fP, \fBcorectl\-run(1)\fP, \fBcorectl\-ssh(1)\fP, \fBcorectl\-version(1)\fP


.SH HISTORY
.PP
