.TH "coreos" "1" "" " " ""  ""


.SH NAME
.PP
coreos load \- Loads from an instrumentation file (in TOML, JSON or YAML) one or more CoreOS instances


.SH SYNOPSIS
.PP
\fBcoreos load\fP [OPTIONS]


.SH DESCRIPTION
.PP
Loads from an instrumentation file (in TOML, JSON or YAML) one or more CoreOS instances


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users


.SH EXAMPLE
.PP
.RS

.nf
  coreos load profiles/demo.toml

.fi
.RE


.SH SEE ALSO
.PP
\fBcoreos(1)\fP,


.SH HISTORY
.PP
