.TH "coreos" "1" "" " " ""  ""


.SH NAME
.PP
coreos\-pull \- Pulls a CoreOS image from upstream


.SH SYNOPSIS
.PP
\fBcoreos pull\fP [OPTIONS]


.SH DESCRIPTION
.PP
Pulls a CoreOS image from upstream


.SH OPTIONS
.PP
\fB\-\-channel\fP="alpha"
    CoreOS channel

.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    override local image, if any

.PP
\fB\-\-version\fP="latest"
    CoreOS version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users


.SH SEE ALSO
.PP
\fBcoreos(1)\fP


.SH HISTORY
.PP
