.TH "corectl" "1" "" " " ""  ""


.SH NAME
.PP
corectl\-version \- Shows corectl version information


.SH SYNOPSIS
.PP
\fBcorectl version\fP [OPTIONS]


.SH DESCRIPTION
.PP
Shows corectl version information


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
