.TH "corectl" "1" "" " " ""  ""


.SH NAME
.PP
corectl\-ls \- Lists locally available CoreOS images


.SH SYNOPSIS
.PP
\fBcorectl ls\fP [OPTIONS]


.SH DESCRIPTION
.PP
Lists locally available CoreOS images


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
    browses all channels

.PP
\fB\-\-channel\fP="alpha"
    CoreOS channel

.PP
\fB\-j\fP, \fB\-\-json\fP[=false]
    outputs in JSON for easy 3rd party integration


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
