.TH "coreos" "1" "" " " ""  ""


.SH NAME
.PP
coreos version \- Show the (coreos\-xhyve) version information


.SH SYNOPSIS
.PP
\fBcoreos version\fP [OPTIONS]


.SH DESCRIPTION
.PP
Show the (coreos\-xhyve) version information


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users


.SH SEE ALSO
.PP
\fBcoreos(1)\fP,


.SH HISTORY
.PP
