.TH "corectl" "1" "" " " ""  ""


.SH NAME
.PP
corectl\-rm \- Removes one or more CoreOS images from local fs


.SH SYNOPSIS
.PP
\fBcorectl rm\fP [OPTIONS]


.SH DESCRIPTION
.PP
Removes one or more CoreOS images from local fs


.SH OPTIONS
.PP
\fB\-\-channel\fP="alpha"
    CoreOS channel

.PP
\fB\-\-old\fP[=false]
    removes outdated images

.PP
\fB\-\-version\fP="latest"
    CoreOS version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
