#!/bin/bash

getVersionID () {
    declare channel="$1"
    v_url="http://${channel}.release.core-os.net/amd64-usr/current/version.txt"
    curl -Lsk "${v_url}" | grep COREOS_VERSION_ID= | sed -e 's,.*=,,'
}

CHANNEL=${CHANNEL:-alpha}
VERSION=${VERSION:-$(getVersionID ${CHANNEL})}
MEMORY=${MEMORY:-1024}

VMLINUZ=${CHANNEL}.${VERSION}.coreos_production_pxe.vmlinuz
INITRD=${CHANNEL}.${VERSION}.coreos_production_pxe_image.cpio.gz
CMDLINE="earlyprintk=serial console=ttyS0 acpi=off coreos.autologin"

if [ $# -ne 1 ]; then
	CMDLINE="${CMDLINE} cloud-config-url=https://raw.githubusercontent.com/coreos/coreos-xhyve/master/cloud-init/docker-only.txt"
fi

MEM="-m ${MEMORY}M"
#SMP="-c 2"
NET="-s 2:0,virtio-net"
PCI_DEV="-s 0:0,hostbridge -s 31,lpc"
LPC_DEV="-l com1,stdio"

sudo xhyve $MEM $SMP $PCI_DEV $LPC_DEV $NET $IMG_HDD -f kexec,imgs/$VMLINUZ,imgs/$INITRD,"$CMDLINE"
